### ISSUE TITLE
Error in iOS with .podspec 

### ISSUE THREAD

**Issue by Mirott** [qonversion/capacitor-plugin#10]
` No podspec found for `QonversionCapacitorPlugin` in `../../node_modules/@qonversion/capacitor-plugin``

The error disappears after changing the file name from **QonversionCapacitor.podspec** to **QonversionCapacitorPlugin.podspec**

**Comment by SpertsyanKM** [comment]
Hi @Mirott,

Thanks for bringing this issue to our attention. We’re currently working on a fix and will keep you updated. I’ll let you know as soon as it’s resolved.

**Comment by SpertsyanKM** [comment]
A new version, [0.1.1](https://github.com/qonversion/capacitor-plugin/releases/tag/0.1.1), has just been released that addresses this issue. Please upgrade to the latest version. I’ll go ahead and close this issue, but don’t hesitate to reopen it or create a new one if you have any additional questions.
